site_name: ArcLab Studio
site_description: Entorno de desarrollo, simulación lógica y RTL estructurado.
site_url: https://thenicolen.github.io/ArcLab/ 

theme:
  name: material
  logo: assets/app_icon.ico
  favicon: assets/app_icon.ico
  palette:
    scheme: slate
    primary: black
    accent: cyan
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Inicio: index.md
  - Tutoriales: tutoriales.md
  - Descargas: descargas.md
  - Patch Logs: changelog.md